# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{throttler}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hakan Ensari"]
  s.date = %q{2010-07-23}
  s.description = %q{Throttles the frequency at which concurrently-running Ruby blocks are executed.}
  s.email = %q{code@papercavalier.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "lib/throttler.rb"
  ]
  s.homepage = %q{http://github.com/papercavalier/throttler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Throttles the frequency at which concurrently-running Ruby blocks are executed.}
  s.test_files = [
    "spec/fixtures/foo.rb",
     "spec/spec_helper.rb",
     "spec/throttler_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

